{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-backend-env" (include "bingo.fullname" .))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bingo.fullname" . }}-backend-env
type: Opaque
{{ if $secret -}}
data:
  ADMIN_PASS: {{ index $secret.data "ADMIN_PASS" }}
  JWT_SECRET: {{ index $secret.data "JWT_SECRET" }}
{{ else -}}
stringData:
  ADMIN_PASS: {{ .Values.backend.adminPassword | default (randAlphaNum 16) | quote }}
  JWT_SECRET: {{ .Values.backend.jwtSecret | default (randAlphaNum 48) | quote }}
{{ end }}