apiVersion: v1
kind: Service
metadata:
  name: {{ include "bingo.fullname" . }}-backend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "bingo.selectorLabels" . | nindent 4 }}
    app: backend